### ISSUE TITLE
fix: zero sequence magnetisation information 

### ISSUE THREAD

**Issue by FiedLa** [ieeh-tu-dresden/power-system-data-model#38]
please add zero sequence magnetisation information :-)
![grafik](https://github.com/ieeh-tu-dresden/power-system-data-model/assets/122098671/d0507316-1056-42be-8600-e6c2ef7ba6a7)

**Comment by SebastianDD** [comment]
zx0hl_n
rtox0_n

What is the recommended way to store the related values (which name)? Like Leerlaufstrom and Eisenverluste are single values and not a impedance ratio like the both requested.

**Comment by FiedLa** [comment]
i have no preferred solution. you could either export them as they are oder calculate the corresponding reactances / resistances. 
![grafik](https://github.com/ieeh-tu-dresden/power-system-data-model/assets/122098671/26451870-7f21-4859-8aea-4b8a13c3e290)
or you could also calculate the i_0 und PFE for the zero sequence from these values. (would be probably the cleanest way) 
additional information: these values are only required for YNy, Yyn, Yy and YNyn transformers, which is a bit strange because theoretically they are not necessary for the calculation.
